### PR TITLE
how install Bundler in registery for make composer install more easy

### PR DESCRIPTION
**Pull request by didungar**

### CODE REVIEW

**Comment by didungar** [comment]
i can't try with my fork, but this will help to be more easy for install.

**Comment by GromNaN** [comment]
Using [flex](https://symfony.com/doc/current/setup/flex.html), packages with "symfony-bundle" type are automatically added to the `bundles.php`. I don't get why this post-install-cmd would be necessary.

Do you know other bundles that provide such feature?

**Comment by didungar** [comment]
Ok, the README led me astray.
It said : "Next, register the bundle in your `config/bundles.php`:"

As you mentioned, is'nt necessary with the manifest.json

**Comment by GromNaN** [comment]
Could you submit a PR to update the readme?

**Pull request closed without merging**
