### PR TITLE
Upgrade `openai-php/client`

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Review by GromNaN — APPROVED** [review]
Thank you @OskarStark

**Review by GromNaN — CHANGES_REQUESTED** [review]
Approved to fast. There is a failing test.

**Comment by OskarStark** [comment]
As the last commits from 11.08.2023, not sure it's failing due to the PR. I need to investigate.

**Comment by OskarStark** [comment]
Closing in favor of #10

**Pull request closed without merging**
